services:
  reservas_api:
    build:
      context: ./reservas_api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: reservas_api
    restart: unless-stopped
    ports:
      - "81:8080"

  usuarios_api:
    build:
      context: ./usuarios_api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: usuarios_api
    restart: unless-stopped
    ports:
      - "82:8080"
  admin_api:
    build:
      context: ./admin_api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: admin_api
    restart: unless-stopped
    ports:
      - "83:8080"